#! /bin/sh
### BEGIN INIT INFO
# Provides:          puppet-autosign
# Required-Start:    $syslog $time
# Required-Stop:     $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Adds and removes nodes from puppet control
# Description:       Debian init script for the puppet-autosign daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bmj/bin/puppet-autosign.rb
PIDFILE=/var/run/puppet-autosign.pid

set -a
[ -f /etc/default/puppet-autosign ] && . /etc/default/puppet-autosign
set +a

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	  log_daemon_msg "Starting puppet-autosign"
	  start_daemon -p $PIDFILE $DAEMON
	  log_end_msg $? ;;
  stop)
	  log_daemon_msg "Stopping puppet-autosign"
	  killproc -p $PIDFILE $DAEMON
	  log_end_msg $? ;;
  force-reload|restart)
    $0 stop
    $0 start ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON puppet-autosign && exit 0 || exit $? ;;
  *)
    echo "Usage: /etc/init.d/puppet-autosign {start|stop|restart|force-reload|status}"
    exit 1 ;;
esac

exit 0
